version: '3.8'
services:
  minecraft-bedrock:
    image: itzg/minecraft-bedrock-server
    container_name: bedrock-server
    restart: unless-stopped
    ports:
      - "19132:19132/udp"
    environment:
      - EULA=TRUE
      - OPS=killerlala150
      - LEVEL_NAME=world # The server looks for a folder named 'world'
    volumes:
      # This maps the /world folder in your repo 
      # directly to the folder the server expects.
      - ./world:/data/worlds/world
