version: "3"
services:
  bedrock-server:
    image: itzg/minecraft-bedrock-server
    container_name: bedrock-server
    environment:
      - EULA=TRUE
      - ALLOW_CHEATS=true
      - OPS=Killerlala150,2535471448557756
      - DEFAULT_PLAYER_PERMISSION_LEVEL=operator
      - LEVEL_NAME=world
      - VIEW_DISTANCE=20
    ports:
      - "19132:19132/udp"
    volumes:
      # This points the container to your permanent VPS folder
      - /var/lib/minecraft-data/world:/data/worlds/world
    stdin_open: true
    tty: true
    restart: unless-stopped
